// <auto-generated />
using System;
using Alex_Chasi_Person_Test_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alex_Chasi_Person_Test_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251115050517_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alex_Chasi_Person_Test_Api.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Principal 123",
                            Age = 30,
                            City = "Quito",
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2025, 11, 15, 5, 5, 16, 970, DateTimeKind.Utc).AddTicks(4985),
                            Email = "juan.perez@example.com",
                            Name = "Juan Pérez",
                            PhoneNumber = "+593991234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Av. Amazonas 456",
                            Age = 25,
                            City = "Guayaquil",
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2025, 11, 15, 5, 5, 16, 970, DateTimeKind.Utc).AddTicks(4990),
                            Email = "maria.garcia@example.com",
                            Name = "María García",
                            PhoneNumber = "+593987654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calle Sucre 789",
                            Age = 35,
                            City = "Cuenca",
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2025, 11, 15, 5, 5, 16, 970, DateTimeKind.Utc).AddTicks(4993),
                            Email = "carlos.rodriguez@example.com",
                            Name = "Carlos Rodríguez",
                            PhoneNumber = "+593971112222"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
